VA-4212 Publish to Social Jobs
vimeo/vimeo-networking-java pull request #405
Opened 2020-01-08 22:21 UTC by howardrigberg

#### Issue
- https://vimean.atlassian.net/browse/VA-4212
- https://vimean.atlassian.net/browse/VA-4213

#### Summary
Added support for GET and PUT requests to /videos/{video_id}/publish_to_social

#### How to Test
Test setup is a bit complicated. See me IRL if you want instructions for testing in the app.

2020-01-09 15:33 UTC, anthonycr requested changes

2020-01-09 15:33 UTC, anthonycr commented on models/src/main/java/com/vimeo/networking2/PublishToFacebookPost.kt
> +        val title: String,
This and all properties in this class should be nullable with a default value of null. This comment also applies to
- `PublishToLinkedInPost`
- `PublishToTwitterPost`
- `PublishToYouTubePost`

Unless the API ignores field filters for these non null properties they should be made null.

2020-01-09 15:33 UTC, anthonycr commented on models/src/main/java/com/vimeo/networking2/PublishToYouTubePost.kt
> +        val privacy: String,
Should have a corresponding enum if I understand the documentation correclty

2020-01-09 16:26 UTC, WhosNickDoglio approved these changes
The only change I was going to mention was the enum for Privacy that @anthonycr already mentioned. 

Everything else looks good. 👍

2020-01-10 15:31 UTC, anthonycr commented
@howardrigberg I can review after you resolve the merge conflicts.

2020-01-10 21:45 UTC, howardrigberg commented
@anthonycr  Thanks for the review. I moved the param objects into a new package called "params" to distinguish them from the other models. I added the necessary enum and used  `@SerializedName` to ensure that all params will get serialized to the body of the put request correctly.

@WhosNickDoglio I renamed your `PublishJobDestinations` class to `PublishJobAttempts` to resolve a merge conflict and give the class a name that more accurately reflects its purpose. Please let me know if it passes your functional tests and that you agree with my changes.

2020-01-10 21:56 UTC, WhosNickDoglio commented
> @WhosNickDoglio I renamed your `PublishJobDestinations` class to `PublishJobAttempts` to resolve a merge conflict and give the class a name that more accurately reflects its purpose. Please let me know if it passes your functional tests and that you agree with my changes.

No issues with name changes and just tested and everything looks good. 👍

2020-01-13 16:37 UTC, anthonycr requested changes

2020-01-13 16:37 UTC, anthonycr commented on models/build.gradle
> +    api "com.squareup.retrofit2:converter-gson:2.5.0"
Please use Moshi, we are not using Gson going forward.

2020-01-13 20:27 UTC, anthonycr approved these changes
LGTM!

2020-01-13 20:28 UTC, merged