Support download property on Video
vimeo/vimeo-networking-java pull request #494
Opened 2021-06-17 15:48 UTC by anthonycr

# Summary
We need to move away from using the `video.play.progressive` representation and to start using the `video.download` representation. The first stop of this is to add the `download` property to `Video`. This property introduces a new `DownloadableVideoFile` which differs slightly from existing video files. It does not have a log link to log playback. The `Video.download` property is of the type `List<DownloadableVideoFile>`. I also had to add a new `VideoQualityType` that we were not representing in the enum.

## Other changes
- Updated code style guidelines to support new android studio
- Fixed existing detekt warnings in `Video`.
- Fixed naming issues with files used in a JVM environment for `Billing`, `ProgrammedContentItem`, `TeamMembership`, `VideoStatus`, and `Connection`.

2021-06-22 16:40 UTC, howardrigberg requested changes
Looks good. Just some minor suggestions on the docs.

2021-06-22 16:40 UTC, howardrigberg commented on models/src/main/java/com/vimeo/networking2/DownloadableVideoFile.kt
> + * @param md5 The MD5 hash of the file.
Missing docs for `link` and `linkExpirationTime `.

2021-06-22 16:40 UTC, howardrigberg commented on models/src/main/java/com/vimeo/networking2/DownloadableVideoFile.kt
> + * @see VideoQualityType
`@see VideoSourceType`

2021-06-22 16:40 UTC, howardrigberg commented on models/src/main/java/com/vimeo/networking2/Video.kt
> + * @param fileTransferPage Information about the file transfer page associated with this video. This data requires a
Optional: All other fields are alphabetized, could also shuffle order of `fileTransferPage`, `editSession`, and `isPlayable` so they match.

2021-06-24 18:51 UTC, anthonycr commented on models/src/main/java/com/vimeo/networking2/DownloadableVideoFile.kt
> + * @param md5 The MD5 hash of the file.
Since they are documented on the `VideoFile` interface, the documentation is inherited so we don't need to add param docs!

2021-06-24 19:14 UTC, anthonycr commented
@howardrigberg this PR is ready for review, thanks for taking a look.

2021-06-24 19:16 UTC, howardrigberg approved these changes

2021-06-24 19:28 UTC, merged